### ISSUE TITLE
LCFS - BUG - Report history display, BCeID, Submitted status

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1002] opened 2024-10-01 22:41 UTC
**Describe the Bug**
Unformatted internal workflow text is appearing in the Report history in Submitted status for BCeID users. It should only display the Signed & submitted info (until the report is Assessed).

![Image](https://github.com/user-attachments/assets/f36f0228-438a-4d46-b657-85a2bf9fbb47)

https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/184006495/simulate/sitemap

**Expected Behaviour**
A compliance report in submitted status should look like the mock-up for BCeID users, the Report history should only contain info of when the user signed and submitted the report to government. The unformatted text appearing should only be visible on the IDIR side and formatted as per cards...

**Comment by Grulin** [comment] 2024-10-07 19:34
A compliance report in a submitted status isn't currently showing the report history box. Currently it is showing the 'Important information" and "Organization detail" boxes, but is missing the "Report history" box to the far left that should look the same as the wireframe:
![Image](https://github.com/user-attachments/assets/492f673b-5fe6-4540-9198-2a21809338b3)

**Comment by hamed-valiollahi** [comment] 2024-10-10 16:10
Thanks for testing, Lindsy! The issue is fixed now.

**Closed** 2024-10-15 23:05 UTC
Labels: bug, Compliance Reporting, Medium, Tested :)
