### ISSUE TITLE
LCFS - BUG - Fuel type other

### ISSUE THREAD

**Issue by airinggov** [bcgov/lcfs#1243] opened 2024-11-15 16:05 UTC
**Describe the Bug**
The “Fuel type other”, "Units" and "Energy density" fields are incorrectly being enabled when “Other diesel fuel” is selected under “Fuel type”. This should only occur when “Other” is selected under “Fuel type”.

![Image](https://github.com/user-attachments/assets/28fb7db3-457f-4d25-bb05-87765987eda8)

**Expected Behaviour**
The “Fuel type other”, "Units" and "Energy density" fields should only be enabled when “Other” is selected under “Fuel type” and remain disabled for all other fuel type selections.

When "Other diesel fuel" is selected the "Fuel type other" field should remain locked and null. "Units" should remain locked and have the associated value from look-up table. "Energy density" should remain locked and have the associated value from look-up table.

**Actual Behaviour**
The “Fuel type other” field is enabled when “Other diesel fuel” is selected under “Fuel type”.

**Implications**
This could lead to data inconsistencies and incorrect reporting in both “Fuel supply” and “Export fuel” schedules, as the “Fuel type other” field is not meant to be editable unless “Other” is selected.

**Steps To Reproduce**
1. Navigate to the “Fuel supply” or “Export fuel” schedules.
2. Select “Other diesel fuel” under the “Fuel type” dropdown.
3. Observe that the “Fuel type other”, "Units" and "Energy density" fields are enabled, which is incorrect.
4. Switch the selection to “Other” under “Fuel type”.
5. Observe that the “Fuel type other” field remains enabled as expected.

**Additional Context**
- This issue occurs consistently in both the “Fuel supply” and “Export fuel” schedules.
- Review any related validation logic to ensure correctness.

**Comment by Grulin** [comment] 2024-11-21 16:33
Hi @AlexZorkin I know there was a bit of discussion on this bug about whether we need the "Other Diesel" option and we actually do. It looks like it has been removed from the choices for Fuel type, but we do need it as it is listed in the Technical Regs with a specific energy density assigned to it. I checked with the verification team and they confirmed that this is related to a specific fuel type that is distinct from the "Other" option. The explanation was: 

**The other diesel fuel option represents fischer-tropsch diesel which is the diesel with the lowest energy content we are aware of**

For this "Other Diesel" fuel type, the "Fuel type other" field should remain locked and null. "Units" should remain locked and have the associated value from look-up table (L). "Energy density" should remain locked and have the associated value from look-up table (36.51).

Apologies for the confusion on this one

**Closed** 2024-12-12 00:29 UTC
Labels: bug, Compliance Reporting, Medium, Tested w/ issues
